---
- name: Setting up this machine
  hosts: localhost

  roles:
    - role: apt-commons
      become: true
      tags:
        - commons
    - role: docker
      become: true
      vars:
        docker_users: "{{ ansible_user }}"
      tags: 
        - docker
    - role: terminator
      tags:
        - terminator
    - role: ohmyzsh
      tags:
        - ohmyzsh
    - role: pycharm
      become: true
      tags:
        - pycharm
    - role: vscode
      become: true
      tags:
        - vscode
    - role: anydesk
      become: true
    - role: slack
      become: true
      tags:
        - slack
    - role: gnome
      become: true
      tags:
        - gnome
