---
- name: Setting up this machine
  hosts: localhost

  # roles:
  #   - role: commons
  #     become: true
  #   - role: docker
  #     become: true
  #     vars:
  #       docker_users: "{{ ansible_user }}"
  #   - role: terminator
  #   - role: ohmyzsh
  #   - role: pycharm
  #     become: true
  #   - role: anydesk
  #     become: true
  #   - role: slack
  #     become: true
  #   - role: gnome
  #     become: true