---
- name: Ensure dependencies are installed
  apt:
    name: tar 
    state: present

- name: Create PyCharm installation directory
  file:
    path:  "{{ pycharm_install_directory }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0755
    state: directory

- name: Installing PyCharm {{ pycharm_edition }}-{{ pycharm_version }}
  unarchive:
    remote_src: yes
    src:        "{{ pycharm_download_url }}"
    dest:       "{{ pycharm_download_directory }}"
    owner:	    "{{ ansible_user }}"
    group:      "{{ ansible_user }}"

- name: Ensure direct access directory exist for {{ ansible_user }} user
  file:
    path:   "{{ pycharm_direct_access_directory }}"
    state:  directory
    owner:  "{{ ansible_user }}"
    group:  "{{ ansible_user }}"
    mode:   0700

- name: PyCharm desktop entry
  template:
    src:   pycharm-desktop.j2
    dest:  "{{ pycharm_desktop_file }}"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode:  0600
