---
- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present

- name: Install microsoft package gpg key
  become: true
  ansible.builtin.apt_key:
    url: "{{ visual_studio_code_mirror }}/keys/microsoft.asc"
    keyring: "/etc/apt/trusted.gpg.d/packages.microsoft.gpg"
    state: present

- name: Add vscode repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode

- name: Install VScode
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: code