- name: Install docker-compose in "x86_64" architecture
  get_url:
    url:  "{{ docker_compose_url }}"
    dest: "{{ docker_compose_installation_path }}"
    mode: 0755
  when:
    - ansible_architecture == "x86_64"


- name: Install docker-compose in "arm7l" architecture
  when:
    - ansible_architecture == "armv7l"
  block:

  - name: Install dependencies
    package:
      name:   "{{ item }}"
      state:  "{{ docker_compose_dependencies_status }}"
    loop: "{{ docker_compose_dependencies }}"

  - name: Install docker-compose
    pip:
      name:   "{{ docker_compose_pip_name }}"
      state:  "{{ docker_compose_status }}"